version: '3.8'

services:
  mongo:
    image: mongo:8.0
    container_name: mongo
    # ports:
    #   - "40000:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ""
      MONGO_INITDB_ROOT_PASSWORD: ""

  ollama:
    build:
      context: .
      dockerfile: libreria/Dockerfile
      target: ollama
    container_name: ollama
    # ports:
    #   - "40001:11434"
    environment:
      OLLAMA_HOST: "0.0.0.0"
      OLLAMA_MODELS: "/ollama/"

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    ports:
      - "8001:8001"
    depends_on:
      - mongo
      - ollama
    environment:
      MONGO_URI: "mongodb://mongo:27017"
      OLLAMA_BASE_URL: "http://ollama:11434"

  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    container_name: webapp
    depends_on:
      - backend
    ports:
      - "8000:80"